### PR TITLE
Ensure iframe is not undefined.

### LINKED ISSUE #398: Email display error
Test mail not show correct:

Console log error:

Same email show perfect with old maildev docker

Original test message attached:
[il3Q4M3X.eml.txt](https://github.com/maildev/maildev/files/8352547/il3Q4M3X.eml.txt)

### PR DESCRIPTION
**Pull request by djfarrelly**
### Description

Prior to the 2.0 release, the `iframe` was set at the highest level of the closure, but it no longer is, so instead of setting and reading that variable, this passes it as an argument or searches the page for it.

Fixes #398, #411, #403

### CODE REVIEW

File: app/scripts/controllers/item.js [hunk 1]
```diff
@@ -4,172 +4,211 @@
  * Email item Controller -- The UI for the email pane
  */
 
-app.controller('ItemCtrl', [
-  '$scope', '$rootScope', '$routeParams', '$location', 'Email', '$http', '$cookies',
-  function ($scope, $rootScope, $routeParams, $location, Email, $http, $cookies) {
-    const iframe = null
```
Comment (djfarrelly) [inline app/scripts/controllers/item.js:10]: Lots of auto-formatting in this file - this is what was removed and we no longer use this higher level variable in the closure.
